-- ═══════════════════════════════════════════════════════════════════════
-- Curva Fetal — schema do banco (Supabase / Postgres)
--
-- Como rodar:
--   1. Painel do Supabase → SQL Editor → New query
--   2. Cole este arquivo inteiro e clique em "Run"
--   3. Pode rodar de novo sem medo: os "if not exists" e "or replace"
--      fazem isso ser seguro rodar mais de uma vez (idempotente).
--
-- O que isso cria:
--   - 3 tabelas: patients, gestacoes, exams (mesmos campos que o app já usa)
--   - Row Level Security (RLS) em todas: cada linha só é visível/editável
--     por quem a criou (auth.uid()) — mesmo com a chave pública anon,
--     ninguém enxerga dado de outro usuário.
--   - created_at / updated_at automáticos, como início de trilha de
--     auditoria (quem mexeu por último e quando).
--   - id "generated by default as identity": o app escolhe o próprio id
--     (contador interno, igual sempre funcionou) em vez de esperar o banco
--     gerar — banco só gera sozinho se o app não mandar nenhum.
--
-- Já rodou este arquivo antes (versão com "generated always as identity")?
-- Não precisa rodar tudo de novo — vá direto no supabase/migrations/
-- 001_identity_by_default.sql, que só ajusta essa parte.
-- ═══════════════════════════════════════════════════════════════════════

-- ── Função utilitária: mantém updated_at sempre atualizado ──
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════
-- PATIENTS
-- ═══════════════════════════════════════════════════════════════════════
create table if not exists public.patients (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  cpf          text not null,
  nome         text not null default '',
  excluido_em  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists patients_user_id_idx on public.patients(user_id);
create index if not exists patients_cpf_idx      on public.patients(user_id, cpf);

drop trigger if exists set_updated_at on public.patients;
create trigger set_updated_at
  before update on public.patients
  for each row execute function public.set_updated_at();

alter table public.patients enable row level security;

drop policy if exists "patients: dono pode tudo" on public.patients;
create policy "patients: dono pode tudo"
  on public.patients
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ═══════════════════════════════════════════════════════════════════════
-- GESTACOES
-- ═══════════════════════════════════════════════════════════════════════
create table if not exists public.gestacoes (
  id                        bigint generated by default as identity primary key,
  user_id                   uuid not null default auth.uid() references auth.users(id) on delete cascade,
  paciente_id               bigint not null references public.patients(id) on delete cascade,
  dum                       date,
  dpp                       date,
  data_inicio               date,
  gestas                    integer,
  partos                    integer,
  abortos                   integer,
  antecedentes_obstetricos  text not null default '',
  status                    text not null default 'ativa'
                              check (status in ('ativa','finalizada','aborto','ectopica','obito_fetal')),
  observacoes               text not null default '',
  ig_base_data              date,
  ig_base_valor             integer,
  ig_base_tipo              text check (ig_base_tipo in ('DUM','US')),
  tipo_gestacao             text not null default 'unica'
                              check (tipo_gestacao in ('unica','gemelar')),
  corionicidade             text
                              check (corionicidade in ('dicorionica_diamniotica','monocorionica_diamniotica','monocorionica_monoamniotica')),
  excluido_em               timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists gestacoes_user_id_idx     on public.gestacoes(user_id);
create index if not exists gestacoes_paciente_id_idx on public.gestacoes(paciente_id);

drop trigger if exists set_updated_at on public.gestacoes;
create trigger set_updated_at
  before update on public.gestacoes
  for each row execute function public.set_updated_at();

alter table public.gestacoes enable row level security;

drop policy if exists "gestacoes: dono pode tudo" on public.gestacoes;
create policy "gestacoes: dono pode tudo"
  on public.gestacoes
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ═══════════════════════════════════════════════════════════════════════
-- EXAMS
-- ═══════════════════════════════════════════════════════════════════════
create table if not exists public.exams (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  gestacao_id      bigint not null references public.gestacoes(id) on delete cascade,
  data_exame       date not null,
  ig_dias_manual   integer,
  dbp              numeric,
  cc               numeric,
  ca               numeric,
  femur            numeric,
  dof              numeric,
  ccn              numeric,
  umero            numeric,
  radio            numeric,
  ulna             numeric,
  tibia            numeric,
  fibula           numeric,
  au_ip            numeric,
  au_fluxo         text,
  acm_ip           numeric,
  acm_psv          numeric,
  aut_e            numeric,
  aut_d            numeric,
  dv_ip            numeric,
  dv_onda          text,
  cpr              numeric,
  colo             numeric,
  ila              numeric,
  bolsao           numeric,
  feto             text check (feto in ('A','B')),
  excluido_em      timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists exams_user_id_idx     on public.exams(user_id);
create index if not exists exams_gestacao_id_idx on public.exams(gestacao_id);

drop trigger if exists set_updated_at on public.exams;
create trigger set_updated_at
  before update on public.exams
  for each row execute function public.set_updated_at();

alter table public.exams enable row level security;

drop policy if exists "exams: dono pode tudo" on public.exams;
create policy "exams: dono pode tudo"
  on public.exams
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
