-- ═══════════════════════════════════════════════════════════════════════
-- Migração 001 — permite o app escolher o id ao criar paciente/gestação/exame
--
-- Por quê: até agora o banco só existia, mas o app ainda salvava tudo no
-- navegador. Agora que o app passa a gravar direto no Supabase, ele precisa
-- continuar usando o mesmo contador de id que sempre usou (importante para
-- os dados já digitados durante os testes não baterem id com nada por
-- coincidência). Isso só é possível se o banco permitir id explícito —
-- por padrão (schema.sql original) ele exigia gerar sozinho.
--
-- Como rodar: SQL Editor do Supabase → cole isto → Run. Seguro rodar mais
-- de uma vez.
-- ═══════════════════════════════════════════════════════════════════════

alter table public.patients  alter column id set generated by default;
alter table public.gestacoes alter column id set generated by default;
alter table public.exams     alter column id set generated by default;
